---
- hosts: JbossAS_5
  remote_user: s_ansible
  become: yes
  vars:
    app: app
    package: ear 
    backup_path: /bkp/
    deploy_path:  path
    download_folder: path
    download_url: URL
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  tasks:
  - name: Download Package
    get_url: url={{download_url}} dest={{download_folder}} validate_certs=no url_username=user url_password=pass owner=jboss group=jboss

  - name: Backup Old Package
    command: "cp -pr {{deploy_path}}/{{package}} {{backup_path}}{{package}}.{{date}}"

  - name: Deploy 
    command: "cp -pr {{download_folder}}/{{package}} {{deploy_path}}/{{package}}"

