---
- hosts: JbossAS_5
  remote_user: s_ansible
  become: yes
  vars:
    app: gestaonet
    package: sipac.ear 
    backup_path: /bkp/
    deploy_path: /opt/jboss/server/gestaonet1/deploy/
    download_folder: /home/ATUALIZACOES/gestaonet
    #download_url: "https://sistemas.dpf.gov.br/nexus/repository/maven-releases/br/gov/dpf/{{app}}/{{package}}"
    download_url: https://sistemas.dpf.gov.br/nexus/repository/maven-releases/br/gov/dpf/assinatura/1.0.2/assinatura-1.0.2.war
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  tasks:
  - name: Download Package
    get_url: url={{download_url}} dest={{download_folder}} validate_certs=no url_username=rodrigo.rmv url_password=Redeslpi owner=jboss group=jboss

  - name: Backup Old Package
    command: "cp -pr {{deploy_path}}/{{package}} {{backup_path}}{{package}}.{{date}}"

  - name: Deploy 
    command: "cp -pr {{download_folder}}/{{package}} {{deploy_path}}/{{package}}"

    # jboss: src=/tmp/sipac.20104.ear  deployment=sipac.ear deploy_path=/opt/jboss/server/gestaonet1/deploy state=present

